### ISSUE TITLE
No readme

### ISSUE THREAD

**Issue by markusstephanides** [Birkenstab/ausrede.birkenstab.de#1]
Please add a README.ME file :)

**Comment by Birkenstab** [comment]
Will be added soon

**Comment by markusstephanides** [comment]
Do you have an ETA?

**Comment by Birkenstab** [comment]
I'll add it within a few days

**Comment by Birkenstab** [comment]
I've just added a Readme

**Comment by Birkenstab** [comment]
This project is only useful if you can understand German. Thus an English Readme wouldn't make any sense

**Comment by markusstephanides** [comment]
But how should non-german speakers know that?

**Comment by Birkenstab** [comment]
There is an a topic that says german

**Comment by markusstephanides** [comment]
Hä? There is also a topic "lel". What's the point of that?

**Comment by markusstephanides** [comment]
Censorship is forbidden. Please stop deleting my legitimate quesitons

**Comment by Birkenstab** [comment]
Please stop trolling

**Comment by markusstephanides** [comment]
Then provide a better readme where is is noticed, that this is a german project.

**Comment by markusstephanides** [comment]
Also your readme headings are in english so please choose a language. German or english.

**Comment by Birkenstab** [comment]
The headings are all listed in the german dictionary except for 'Contribution'

**Comment by markusstephanides** [comment]
But "Responsive design" is not in the german dictionary and you wrote "Platformunabhängig" instead of "Plattformunabhängig"

**Comment by Birkenstab** [comment]
Yeah but they are used in German language

**Comment by markusstephanides** [comment]
Also: You specify "Kinderleichte Bedienung". My child (2 weeks old) tried to use it, and it couldn't even figure out how to open the application!!!!!!!!!

**Comment by Birkenstab** [comment]
lol
